import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'



const Home: NextPage = () => {
  const router = useRouter();
  const firstProject = () =>{
    router.push('/morepage/nextPage');
  } 
  const secondProject = () =>{
    router.push('/morepage2/nextPage1');
  } 
  const thirdProject = () =>{
    router.push('/contentPage/mainPage');
  } 
  const fourthProject = () =>{
    router.push('/content2/content2');
  } 
  const fifthProject = () =>{
    router.push('/login/loginPage');
  } 
  const sixthProject = () =>{
    router.push('/signup/signUp');
  } 
  const seventhProject = () =>{
    router.push('/otppage/otpPage')
  } 
  const eigthProject = () =>{
    router.push('/EduApp/eduApp');
  } 
  const ninethProject = () => {
    router.push('/morepage/axiosPage');
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      

        <div className=' w-screen justify-center h-[1000px] flex flex-1 '>
          <div className='bg-slate-400 w-[60%] h-[30%] grid grid-flow-row justify-center px-5 py-5'>
            <div className=' '>
          <button className='h-[100px] w-[100px] bg-white text-white hover:border-2 ml-5 mt-5 rounded-xl bg-gradient-to-r from-[#F85750] to-[#A73F3A]' onClick={firstProject}>Pages</button>
        <button className='h-[100px] w-[100px] bg-white text-white hover:border-2 ml-5 mt-5 rounded-xl bg-gradient-to-r from-[#F39C12] to-[#9C6B1E]' onClick={secondProject}>Pages</button>
        <button className='h-[100px] w-[100px] bg-white text-white hover:border-2 ml-5 mt-5 rounded-xl bg-gradient-to-r from-[#7F8CF1] to-[#444E9C]' onClick={thirdProject}>Card CSS</button>
        <button className='h-[100px] w-[100px] bg-white text-white hover:border-2 ml-5 mt-5 rounded-xl bg-gradient-to-r from-[#7F8CF1] to-[#444E9C]' onClick={fourthProject}>Card Tailwind</button>
        <button className='h-[100px] w-[100px] bg-white text-white hover:border-2 ml-5 mt-5 rounded-xl bg-gradient-to-r from-[#9459D7] to-[#4A3AA7]' onClick={fifthProject}>Login</button>
        <button className='h-[100px] w-[100px] bg-white text-white hover:border-2 ml-5 mt-5 rounded-xl  bg-gradient-to-r from-[#F85750] to-[#A73F3A] ' onClick={sixthProject}>SignUp</button>
        </div>
        <div>
          
          
          <button className='h-[100px] w-[100px] text-white ml-5 mt-5 rounded-xl hover:border-2 bg-gradient-to-r from-[#F85750] to-[#A73F3A] ' onClick={seventhProject}>OTP</button>
           <button className='h-[100px] w-[100px]  text-white ml-5 mt-5 rounded-xl hover:border-2  bg-gradient-to-r from-[#F39C12] to-[#9C6B1E]' onClick={eigthProject}>LMS</button>
           <button className='h-[100px] w-[100px]  text-white ml-5 mt-5 rounded-xl hover:border-2 bg-gradient-to-r from-[#7F8CF1] to-[#444E9C] ' onClick={ninethProject}>9</button>
           <button className='h-[100px] w-[100px]  text-white ml-5 mt-5 rounded-xl hover:border-2 bg-gradient-to-r from-[#9459D7] to-[#4A3AA7] '>10</button>
           </div>
        </div>
        </div>
      

      
      </main>

      
    </div>
  )
}

export default Home
