import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className='text-blue-700'>
      <Link href={'./morepage/nextPage'}  >Link 1</Link>
      </h1>
      <button onClick={()=>{

      }}>Link Button</button>

      <h3 className='text-red-500'>Content<Link href={'./contentPage/mainPage'}>Page </Link></h3>
      <h3>Tailwind Css <Link href={'./content2/content2'}> Content Page  </Link></h3>
      <h3 className='text-red-800'><Link href={'./login/loginPage'}>Login Page</Link></h3>
      
      {/* <div className='h-[200px] w-[550px] bg-black flex text-white text-center justify-center  '>
        <div className='grid grid-flow-col grid-cols-4 grid-rows-1  w-[100%]'>
        <button className='h-[100px] w-[100px] bg-white text-black ml-5 mt-5 rounded-xl'>1</button>
        <button className='h-[100px] w-[100px] bg-white text-black ml-5 mt-5 rounded-xl'>2</button>
        <button className='h-[100px] w-[100px] bg-white text-black ml-5 mt-5 rounded-xl'>3</button>
        <button className='h-[100px] w-[100px] bg-white text-black ml-5 mt-5 rounded-xl'>4</button>
        </div>
        
        </div>

        <div className='h-[200px] w-[550px] bg-black flex text-white text-center justify-center '>
          <div className='grid grid-flow-col grid-cols-4 grid-rows-1  w-[100%]'>
        <button className='h-[100px] w-[100px] bg-white text-black ml-5 mt-5 rounded-xl'>5</button>
        <button className='h-[100px] w-[100px] bg-white text-black ml-5 mt-5 rounded-xl'>6</button>
        <button className='h-[100px] w-[100px] bg-white text-black ml-5 mt-5 rounded-xl'>7</button>
        <button className='h-[100px] w-[100px] bg-white text-black ml-5 mt-5 rounded-xl'>8</button>
        </div>
        
        </div> */}
      

      
      </main>

      
    </div>
  )
}

export default Home
